# Generated by Django 4.0.4 on 2022-04-20 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('well_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('volume', models.FloatField()),
                ('consist', models.TextField()),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='factory.consumer')),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='factory.product'),
        ),
    ]
