# Generated by Django 4.0.4 on 2022-04-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.product'),
        ),
    ]
