# Generated by Django 4.0.4 on 2022-04-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('delivery_man', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='orders_list',
            field=models.ManyToManyField(blank=True, related_name='orders_list', to='order.order'),
        ),
    ]
