# Generated by Django 4.0.4 on 2022-04-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_man', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('workers_list', models.ManyToManyField(blank=True, related_name='workers_list', to='delivery_man.deliveryman')),
            ],
        ),
    ]
