# Generated by Django 4.0.4 on 2022-04-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='products',
        ),
        migrations.AddField(
            model_name='consumer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='user.product'),
        ),
    ]
