# Generated by Django 4.0.4 on 2022-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_consumer_products_consumer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='orders',
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='user.order'),
        ),
    ]
