# Generated by Django 4.0.4 on 2022-04-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('user', '0004_rename_user_id_order_user_remove_order_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='orders_list',
        ),
        migrations.RemoveField(
            model_name='deliveryservice',
            name='workers_list',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='consumer',
        ),
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='order.order'),
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.DeleteModel(
            name='DeliveryMan',
        ),
        migrations.DeleteModel(
            name='DeliveryService',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
